baseline: gcope
stage: ete

general:
  save_dir: storage/gcope/ete_smoke
  cache_dir: storage/.cache
  seed: 777
  few_shot: 1
  reconstruct: 0.0

model:
  backbone:
    model_type: gcn
    hid_dim: 64
    gcn:
      num_conv_layers: 2
      dropout: 0.2
  saliency:
    model_type: none
  answering:
    model_type: mlp

data:
  name: cora
  seed: 777
  node_feature_dim: 32
  supervised:
    ratios: [0.1, 0.1, 0.8]

ete:
  epoch: 1
  batch_size: 8
  learning_rate: 0.001
  weight_decay: 0.00001
  repeat_times: 1
