baseline: gcope
stage: ete

general:
  save_dir: storage/gcope/cora_ete
  cache_dir: storage/.cache
  seed: 777
  few_shot: 1
  reconstruct: 0.0

model:
  backbone:
    model_type: fagcn
    hid_dim: 100
    fagcn:
      num_conv_layers: 2
      dropout: 0.2
      epsilon: 0.1
  saliency:
    model_type: none
  answering:
    model_type: mlp

data:
  name: cora
  seed: 777
  node_feature_dim: 100
  supervised:
    ratios: [0.1, 0.1, 0.8]

ete:
  epoch: 100
  batch_size: 100
  learning_rate: 0.0001
  weight_decay: 0.00001
  repeat_times: 5
