baseline: gcope
stage: finetune

general:
  save_dir: storage/gcope/cora_gcope_rec0
  cache_dir: storage/.cache
  seed: 777
  few_shot: 1
  reconstruct: 0.0

model:
  backbone:
    model_type: fagcn
    hid_dim: 100
    fagcn:
      num_conv_layers: 2
      dropout: 0.2
      epsilon: 0.1
  saliency:
    model_type: none
  answering:
    model_type: mlp

data:
  name: cora
  seed: 777
  node_feature_dim: 100
  supervised:
    ratios: [0.1, 0.1, 0.8]

adapt:
  method: finetune
  pretrained_file: storage/gcope/cora_gcope_rec0/wisconsin,texas,cornell,chameleon,squirrel,citeseer,pubmed,computers,photo_pretrained_model.pt
  epoch: 100
  batch_size: 100
  repeat_times: 5
  finetune:
    backbone_tuning: true
    saliency_tuning: false
    learning_rate: 0.0001
    weight_decay: 0.00001
